### ISSUE TITLE
Unable to save plugins in ./plugins folder

### ISSUE THREAD

**Issue by mauloop** [OokTech/TW5-BobEXE#14]
My environment is: Win10 + Chrome 72 + BobExe 1.2.1.
Bob settings (settings.json in the IndexWiki/settings folder) are as the default.

I tried the following:

1.  install a plugin with drag'n'drop
2. save to folder with "ControlPanel / BobSettings / ManagePlugins"

It did not work. In the cmd shell where Bob was started it logs these messages:

```
WebSocket error:  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:168:7)
    at Object.$tw.nodeMessageHandlers.savePluginFolder ($:/plugins/OokTech/Bob/NodeMessageHandlers.js:1094:37)
    at WebSocket.$tw.Bob.handleMessage ($:/plugins/OokTech/Bob/NodeWebSocketsSetup.js:151:52)
    at WebSocket.emit (events.js:182:13)
    at Receiver.receiverOnMessage ($:/plugins/OokTech/Bob/External/WS/lib/websocket.js:720:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.dataMessage ($:/plugins/OokTech/Bob/External/WS/lib/receiver.js:415:14)
    at Receiver.getData ($:/plugins/OokTech/Bob/External/WS/lib/receiver.js:347:17)
    at Receiver.startLoop ($:/plugins/OokTech/Bob/External/WS/lib/receiver.js:134:22)
```

I also tried to manually copy the plugin.info in ./plugins/mau/myPlugin. I copied it from a working  TW5 on Node.js instance (not Bob). Bob didn't recognizes it and didn't shows it in plugins available for selection.

Finally I tried to manually add it to tiddlywiki.info. The plugin was not loaded. I used the IndexWiki instance without other modifications for all of these tests. 

As I said the same plugin works fine if I load it via tiddlywiki.info in a regular Node.js instance. What's wrong? Was it me?

Please, can you help. I would really like to switch my wikis to Bob, but the chance to save the plugins in one place and serve to all, as I do with Node.js, is essential forme.

Thanks in advance,

)+(

**Comment by inmysocks** [comment]
The copy plugins to plugin folder is very experimental and I will probably remove the interface for it in the next release, so that part isn't you. I think that the problem is probably that the path to the plugins folder isn't set correctly.

To add plugins that will be available to every wiki served by Bob you need to set a plugins path in the configuration. Probably the simplest way to do this is by opening the control panel in the index wiki, opening the `Bob Settings` tab and then the `Manual Settings` tab under that.

You need to add a setting like this:

"pluginsPath": "./Plugins"

To do this follow these steps, I am giving detailed instructions so other people can see them and I have them for including in the documentation later:

- Click on the lowest `+` button in the Manual Settings tab, it is just above the `Update Settings` button
- Two text fields should appear, in the smaller one on top enter `pluginsPath` and in the larger one enter `./Plugins`. Leave the radio button on the default value so that Field is selected.
- Click on the checkmark under the text boxes
- Restart the server by opening the `Server Actions` tab and clicking on `Shutdown Wiki` than reopening Bob
- Now you can make a folder called `Plugins` in the same folder as the Bob executable and place your plugins inside this folder. They must be organised by author, so you would have a folder structure like `./Plugins/OokTech/Calendar` for the calendar plugin by OokTech.
- You can add these plugins to a wiki by opening the wiki and going to the `Manage Plugins` tab under the `Bob Settings` tab. Click on the `Update Plugin List` button to refresh the plugin list then you can use the check boxes below to select which plugins you want in the current wiki. After selecting the plugins you want click the `Save Plugin Selection` then refresh the page. You can use the `Refresh Page` link next to the `Save Plugin Selection` button to do this.

You can place more plugins in the plugins folder to have them available, just make sure that in the plugins folder you have sub-folders for each author and then plugins inside the author folders.

You can change where it checks for plugins by changing the path from `./Plugins` to something else. Both relative and absolute paths should work. I think that `./Plugins` works as a relative path in windows but I am not certain. You may need to change it to something like `.\Plugins`.

It just occurred to me that I should have the plugins folder set to `./Plugins` by default to avoid this problem.

**Comment by mauloop** [comment]
I did not find a working value for `pluginsPath`. I tried with:

- `./Plugins`
- `.\Plugins`
- `.\\Plugins`
- `c:\\Users\\mauloop\\Desktop\\Bob\\Plugins`
- `/Users/mauloop/Desktop/Bob/Plugins`
- ...

Every time I stopped Bob server and then I reloaded both server and browser page and clicked on `Update Plugin List`.

This are my folders:

```
Bob
Bob/IndexWiki
Bob/IndexWiki/settings
Bob/IndexWiki/tiddlers
Bob/Plugins
Bob/Plugins/mau/mautools
Bob/Wikis
Bob/Wikis/bob-test-1
Bob/Wikis/bob-test-1/tiddlers
```

In `Bob/Plugins/mau/mautools` there is a `plugin.info` file for a self-made plugin (this one works fine if placed in the `tiddlywiki/plugins` folder of a regular node.js based Tiddlywiki instance).

I did all of my tests directly with the `IndexWiki` (not `bob-test-1`).

This are setting in `Bob/IndexWiki/settings/settings.json`:

```
{
  "wikis": {
    "bob-test-1": "bob-test-1"
  },
  "ws-server": {
    "host": "127.0.0.1",
    "wssport": 8081,
    "port": "8080"
  },
  "suppressBrowser": "",
  "serverInfo": {
    "ipAddress": "192.168.56.1",
    "port": "8080",
    "host": "127.0.0.1"
  },
  "API": {
    "pluginLibrary": "yes",
    "pluginsPath": "./Plugins"
  },
  "includePluginList": {},
  "excludePluginList": {},
  "wikisPath": "./Wikis"
}
```

The copy plugins to folder feature is not essential to me (I already do it manually with basic node.js setup), but having my plugins stored once in a folder and shared with every wiki. An alternative could be to switch to Bob (not BobExe) and save my plugins in the `tiddlywiki/plugins` folder as usual.

I keep this as the last chance.

P.S.: I tried both relative and absolute paths. Just in case, while defining relative paths I assume the Bob root dir (`C:\Users\mauloop\Desktop\Bob`) as `cwd`. Is this correct?

**Comment by inmysocks** [comment]
The plugins path in your settings is inside the API property, not as a root property. It should be on the same level as wikisPath. That would keep it from working. Other than that it looks like you have everything set up correctly.

And yes, paths should be relative to the folder with the Bob executable, which is your case is `C:\Users\mauloop\Desktop\Bob`.

**Comment by mauloop** [comment]
I don't remeber the cause of this mismatch. I moved both `pluginPath` and `pluginLibrary` keys to the upper level and now it works. Thanks for your help.
